;;-*-coding: utf-8;-*-
(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("afterall" "after all" nil :count 2)
    ("ahve" "have" nil :count 1)
    ("alot" "a lot" nil :count 3)
    ("anywasy" "anyways" nil :count 0)
    ("aorund" "around" nil :count 0)
    ("beatiful" "beautiful" nil :count 0)
    ("beatup" "beat up" nil :count 0)
    ("beisdes" "besides" nil :count 0)
    ("bizzare" "bizarre" nil :count 0)
    ("brightside" "bright side" nil :count 1)
    ("cliche" "cliché" nil :count 0)
    ("coupel" "couple" nil :count 0)
    ("deja" "déjà" nil :count 1)
    ("dont" "don't" nil :count 3)
    ("enitre" "entire" nil :count 0)
    ("exhilerating" "exhilarating" nil :count 0)
    ("fmaily" "family" nil :count 0)
    ("frieends" "friends" nil :count 0)
    ("hse" "she" nil :count 0)
    ("hte" "the" nil :count 0)
    ("htis" "this" nil :count 1)
    ("i'd" "I'd" nil :count 20)
    ("i'll" "I'll" nil :count 20)
    ("i'm" "I'm" nil :count 86)
    ("im" "I'm" nil :count 0)
    ("informaiton" "information" nil :count 0)
    ("iwth" "with" nil :count 2)
    ("jsut" "just" nil :count 2)
    ("layed" "laid" nil :count 0)
    ("migth" "might" nil :count 0)
    ("nevermind" "never mind" nil :count 0)
    ("noone" "no one" nil :count 19)
    ("ofr" "for" nil :count 0)
    ("ot" "to" nil :count 8)
    ("oughtta" "oughta" nil :count 0)
    ("particuarly" "particularly" nil :count 0)
    ("pidgeons" "pigeons" nil :count 0)
    ("proably" "probably" nil :count 0)
    ("racous" "raucous" nil :count 0)
    ("seatbelt" "seat belt" nil :count 0)
    ("si" "is" nil :count 2)
    ("siad" "said" nil :count 0)
    ("siezed" "seized" nil :count 1)
    ("sortof" "sort of" nil :count 0)
    ("taht" "that" nil :count 4)
    ("teh" "the" nil :count 6)
    ("thta" "that" nil :count 1)
    ("volkswagon" "Volkswagen" nil :count 0)
    ("waas" "was" nil :count 0)
    ("wehn" "when" nil :count 0)
   ))

