(defun cf/vlc-grab-timestamp ()
  "docstring"
  (interactive)
  (org-insert-heading)
  (call-process "~/bin/vlc_control.py" nil (buffer-name))
  )

(defun cf/vlc-toggle-pause ()
  (interactive)
  (call-process "~/bin/vlc_control.py" nil nil)
  )
(defun cf/wc-update ()
  (setq-local local-word-count (count-words (point-min) (point-max)))
  )

(defvar cf/writing-dir (expand-file-name "~/dropbox/writing"))
(defun cf/write-today()
  (interactive)
  (setq-local name (concat cf/writing-dir "/unfiled/" (format-time-string "%m_%d_%y") ".org"))
  (find-file name)
  (save-buffer)
  )

(defun cf/display-word (&rest args)
  "Create a buffer for display word instead of using messages.

Slightly hacky to add the word(being defined) into the buffer,
since the rest of the information is generated by define-word,
that may break."
  (interactive)
  (let*
      ((buffer (get-buffer-create "*Define Word*"))
       (word (propertize (substring-no-properties (thing-at-point 'word)) 'face 'bold))
       (header (format "DEFINING: %s \n" word) )
)

    (set-buffer buffer)
    (erase-buffer)
    (set-buffer-major-mode buffer)
    (insert header)
    (apply 'insert args)
    (display-buffer buffer))
  )
