# ~/.config/i3status-rust/config.toml
# icons_format = "{icon}"

[icons]
icons = "awesome4"

[theme]
theme = "native"

[theme.overrides]          # replicate your Gruvbox‑like palette
good_fg      = "#b8bb26"
info_fg      = "#83a598"
warning_fg   = "#fabd2f"
critical_fg  = "#fb4934"


[settings]
interval = 5               # seconds – same as your old file

#################################  Blocks  #################################

# Disk /home  (≈ `disk "/home"` in i3status)
[[block]]
block  = "disk_space"
path   = "/home"
format = "  $available "
# ── CPU ───────────────────────────────────────────────────────────────────────
[[block]]
block    = "cpu"
interval = 2
format   = " $utilization"

[[block.click]]
button = "left"
cmd = "urxvtc -e  bash -c 'htop'"
# ── bash -c 'ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -n 15; read -n 1'"


# ── MEM ───────────────────────────────────────────────────────────────────────
[[block]]
block              = "memory"
interval           = 5              # seconds between updates

# Main display ‑‑ percentage of RAM in use
format             = " $mem_used_percents"

# Alt‑click (or scroll) shows absolute numbers
format_alt         = " $mem_used/$mem_total"

# Optional warnings (change colours automatically)
warning_mem  = 80             # turns theme.warning at ≥80%
critical_mem = 90             # turns theme.critical at ≥90%



# ── Wi‑Fi ─────────────────────────────────────────────────────────────────────
[[block]]
block        = "net"
device = "wlp"
format       = " $signal_strength [$ssid] "

[[block.click]]
button = "left"
cmd = "cinnamon-settings network"

# ── Ethernet ─────────────────────────────────────────────────────────────────
# [[block]]
# block        = "net"
# device= "enp0s31f6"
# format       = "  $ip "

# Dropbox head‑less indicator
[[block]]
block    = "custom"
command  = "~/bin/dropbox-i3bar"
interval = 5
# json     = false           # script prints 3‑line i3blocks style

# ── Volume / Mute ─────────────────────────────────────────────────────────────
[[block]]
block          = "sound"
driver         = "auto"
format = " $icon { $volume|}"
# format         = "  $volume volume_muted`"
# show_volume_when_muted = false
# format_muted = "  0%%"

# ── Music ──────────────────────────────────────────────────────────────────
[[block]]
block      = "music"          # built‑in playerctl wrapper
player     = "spotify"      # fall back to default playerctl discovery
format = " $icon {$combo.str(max_w:40) $prev $play $next |}"
[block.theme_overrides]
idle_bg = "#98971a"
idle_fg = "#333333"

# [[block]]
# block = "hueshift"
# hue_shifter = "redshift"
# step = 50
# click_temp = 3500

# ── Battery ──────────────────────────────────────────────────────────────────
[[block]]
block            = "battery"
missing_format   = ""            # hide completely if no battery
full_format      = " ☻ FULL "
charging_format  = " ⚡ $percentage "
empty_format     = " 🚨 $percentage "
format           = " 🔋 $percentage "

# ── Clock ─────────────────────────────────────────────────────────────────────
[[block]]
block    = "time"
interval = 60
format   = " $timestamp.datetime(f:'%b %d, %H:%M') "
